# Generated by Django 3.1.5 on 2021-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('daft', 'DRAFT'), ('published', 'PUBLISHED')], default='pending', max_length=10)),
            ],
        ),
    ]
