# Generated by Django 3.1.5 on 2021-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_auto_20210126_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='uploads/category/'),
            preserve_default=False,
        ),
    ]
