# Generated by Django 3.1.5 on 2021-01-26 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('suggestion_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('image', models.ImageField(blank=True, upload_to='uploads/occupation/')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('daft', 'DRAFT'), ('published', 'PUBLISHED')], default='pending', max_length=10)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='manager.occupation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
